python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_500 --num-counters 2 --output arm_edge_heterogeneous_InO_500.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_502 --num-counters 2 --output arm_edge_heterogeneous_InO_502.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_503 --num-counters 2 --output arm_edge_heterogeneous_InO_503.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_505 --num-counters 2 --output arm_edge_heterogeneous_InO_505.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_507 --num-counters 2 --output arm_edge_heterogeneous_InO_507.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_508 --num-counters 2 --output arm_edge_heterogeneous_InO_508.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_510 --num-counters 2 --output arm_edge_heterogeneous_InO_510.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_511 --num-counters 2 --output arm_edge_heterogeneous_InO_511.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_519 --num-counters 2 --output arm_edge_heterogeneous_InO_519.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_520 --num-counters 2 --output arm_edge_heterogeneous_InO_520.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_521 --num-counters 2 --output arm_edge_heterogeneous_InO_521.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_523 --num-counters 2 --output arm_edge_heterogeneous_InO_523.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_525 --num-counters 2 --output arm_edge_heterogeneous_InO_525.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_526 --num-counters 2 --output arm_edge_heterogeneous_InO_526.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_527 --num-counters 2 --output arm_edge_heterogeneous_InO_527.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_531 --num-counters 2 --output arm_edge_heterogeneous_InO_531.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_538 --num-counters 2 --output arm_edge_heterogeneous_InO_538.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_541 --num-counters 2 --output arm_edge_heterogeneous_InO_541.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_544 --num-counters 2 --output arm_edge_heterogeneous_InO_544.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_548 --num-counters 2 --output arm_edge_heterogeneous_InO_548.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_549 --num-counters 2 --output arm_edge_heterogeneous_InO_549.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_554 --num-counters 2 --output arm_edge_heterogeneous_InO_554.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_InO_557 --num-counters 2 --output arm_edge_heterogeneous_InO_557.csv

python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_500 --num-counters 2 --output arm_edge_heterogeneous_OOO_500.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_502 --num-counters 2 --output arm_edge_heterogeneous_OOO_502.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_503 --num-counters 2 --output arm_edge_heterogeneous_OOO_503.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_505 --num-counters 2 --output arm_edge_heterogeneous_OOO_505.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_507 --num-counters 2 --output arm_edge_heterogeneous_OOO_507.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_508 --num-counters 2 --output arm_edge_heterogeneous_OOO_508.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_510 --num-counters 2 --output arm_edge_heterogeneous_OOO_510.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_511 --num-counters 2 --output arm_edge_heterogeneous_OOO_511.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_519 --num-counters 2 --output arm_edge_heterogeneous_OOO_519.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_520 --num-counters 2 --output arm_edge_heterogeneous_OOO_520.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_521 --num-counters 2 --output arm_edge_heterogeneous_OOO_521.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_523 --num-counters 2 --output arm_edge_heterogeneous_OOO_523.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_525 --num-counters 2 --output arm_edge_heterogeneous_OOO_525.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_526 --num-counters 2 --output arm_edge_heterogeneous_OOO_526.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_527 --num-counters 2 --output arm_edge_heterogeneous_OOO_527.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_531 --num-counters 2 --output arm_edge_heterogeneous_OOO_531.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_538 --num-counters 2 --output arm_edge_heterogeneous_OOO_538.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_541 --num-counters 2 --output arm_edge_heterogeneous_OOO_541.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_544 --num-counters 2 --output arm_edge_heterogeneous_OOO_544.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_548 --num-counters 2 --output arm_edge_heterogeneous_OOO_548.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_549 --num-counters 2 --output arm_edge_heterogeneous_OOO_549.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_554 --num-counters 2 --output arm_edge_heterogeneous_OOO_554.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_557 --num-counters 2 --output arm_edge_heterogeneous_OOO_557.csv

python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_500 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_500.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_502 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_502.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_503 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_503.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_505 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_505.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_507 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_507.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_508 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_508.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_510 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_510.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_511 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_511.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_519 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_519.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_520 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_520.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_521 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_521.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_523 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_523.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_525 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_525.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_526 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_526.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_527 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_527.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_531 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_531.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_538 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_538.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_541 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_541.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_544 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_544.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_548 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_548.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_549 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_549.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_554 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_554.csv
python3 trace_processing.py --input-list job_lists/arm_edge_heterogeneous_OOO_cache_557 --num-counters 2 --output arm_edge_heterogeneous_OOO_cache_557.csv
