python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_500 --num-counters 4 --output arm_desktop_1.5GHz_500.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_502 --num-counters 4 --output arm_desktop_1.5GHz_502.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_503 --num-counters 4 --output arm_desktop_1.5GHz_503.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_505 --num-counters 4 --output arm_desktop_1.5GHz_505.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_507 --num-counters 4 --output arm_desktop_1.5GHz_507.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_508 --num-counters 4 --output arm_desktop_1.5GHz_508.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_510 --num-counters 4 --output arm_desktop_1.5GHz_510.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_511 --num-counters 4 --output arm_desktop_1.5GHz_511.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_519 --num-counters 4 --output arm_desktop_1.5GHz_519.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_520 --num-counters 4 --output arm_desktop_1.5GHz_520.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_521 --num-counters 4 --output arm_desktop_1.5GHz_521.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_523 --num-counters 4 --output arm_desktop_1.5GHz_523.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_525 --num-counters 4 --output arm_desktop_1.5GHz_525.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_526 --num-counters 4 --output arm_desktop_1.5GHz_526.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_527 --num-counters 4 --output arm_desktop_1.5GHz_527.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_531 --num-counters 4 --output arm_desktop_1.5GHz_531.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_538 --num-counters 4 --output arm_desktop_1.5GHz_538.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_541 --num-counters 4 --output arm_desktop_1.5GHz_541.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_544 --num-counters 4 --output arm_desktop_1.5GHz_544.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_548 --num-counters 4 --output arm_desktop_1.5GHz_548.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_549 --num-counters 4 --output arm_desktop_1.5GHz_549.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_554 --num-counters 4 --output arm_desktop_1.5GHz_554.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_1.5GHz_557 --num-counters 4 --output arm_desktop_1.5GHz_557.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_500 --num-counters 4 --output arm_desktop_3.0GHz_500.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_502 --num-counters 4 --output arm_desktop_3.0GHz_502.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_503 --num-counters 4 --output arm_desktop_3.0GHz_503.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_505 --num-counters 4 --output arm_desktop_3.0GHz_505.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_507 --num-counters 4 --output arm_desktop_3.0GHz_507.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_508 --num-counters 4 --output arm_desktop_3.0GHz_508.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_510 --num-counters 4 --output arm_desktop_3.0GHz_510.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_511 --num-counters 4 --output arm_desktop_3.0GHz_511.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_519 --num-counters 4 --output arm_desktop_3.0GHz_519.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_520 --num-counters 4 --output arm_desktop_3.0GHz_520.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_521 --num-counters 4 --output arm_desktop_3.0GHz_521.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_523 --num-counters 4 --output arm_desktop_3.0GHz_523.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_525 --num-counters 4 --output arm_desktop_3.0GHz_525.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_526 --num-counters 4 --output arm_desktop_3.0GHz_526.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_527 --num-counters 4 --output arm_desktop_3.0GHz_527.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_531 --num-counters 4 --output arm_desktop_3.0GHz_531.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_538 --num-counters 4 --output arm_desktop_3.0GHz_538.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_541 --num-counters 4 --output arm_desktop_3.0GHz_541.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_544 --num-counters 4 --output arm_desktop_3.0GHz_544.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_548 --num-counters 4 --output arm_desktop_3.0GHz_548.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_549 --num-counters 4 --output arm_desktop_3.0GHz_549.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_554 --num-counters 4 --output arm_desktop_3.0GHz_554.csv
python3 humerus_processing.py --input-list job_lists/arm_desktop_3.0GHz_557 --num-counters 4 --output arm_desktop_3.0GHz_557.csv

